config/routes.rb
Rails.application.routes.draw do

    resources :courses do
        resources :classrooms, except: [:index] do
            resources :homeworks, except: [:index]
        end
    end
    authenticated :user do
        root 'index#home'
    end

    unauthenticated :user do
        root 'index#landing'
    end

    devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    #fNLviAvXLrcDO09CqUgw9w
    #E86w1EJTZtsPJ34Q2AASbg
end

app/models/classroom.rb
# == Schema Information
#
# Table name: classrooms
#
#  id         :integer          not null, primary key
#  days       :string
#  start_hour :time
#  end_hour   :time
#  start_day  :date
#  end_day    :date
#  user_id    :integer
#  course_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Classroom < ApplicationRecord
  belongs_to :user
  belongs_to :course
  has_many :homeworks
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]
  before_action :set_course

  # GET /classrooms
  # GET /classrooms.json
  def index
    @classrooms = Classroom.all
  end

  # GET /classrooms/1
  # GET /classrooms/1.json
  def show
    @homework = Homework.new
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /classrooms/1/edit
  def edit
  end

  # POST /classrooms
  # POST /classrooms.json
  def create
    @classroom = current_user.classrooms.new(classroom_params)
    @classroom.course = @course


    respond_to do |format|
      if @classroom.save
        format.html { redirect_to @course, notice: 'Classroom was successfully created.' }
        format.json { render :show, status: :created, location: @classroom }
      else
        format.html { render @course, notice: 'error' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classrooms/1
  # PATCH/PUT /classrooms/1.json
  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to @classroom, notice: 'Classroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @classroom }
      else
        format.html { render :edit }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1
  # DELETE /classrooms/1.json
  def destroy
    @classroom.destroy
    respond_to do |format|
      format.html { redirect_to classrooms_url, notice: 'Classroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    def set_course
        @course = Course.find(params[:course_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classroom_params
      params.require(:classroom).permit(:days, :start_hour, :end_hour, :start_day, :end_day, :course_id)
    end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/views/classrooms/_form.html.erb
<%= form_for([@course, @classroom]) do |form| %>

  <div class="field">
    <%= form.label :days %>
    <%= form.text_field :days %>
  </div>

  <div class="field">
    <%= form.label :start_hour %>
    <%= form.time_select :start_hour %>
  </div>

  <div class="field">
    <%= form.label :end_hour %>
    <%= form.time_select :end_hour %>
  </div>

  <div class="field">
    <%= form.label :start_day %>
    <%= form.date_select :start_day %>
  </div>

  <div class="field">
    <%= form.label :end_day %>
    <%= form.date_select :end_day %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/classrooms/edit.html.erb
<h1>Editing Classroom</h1>

<%= render 'form', classroom: @classroom %>

<%= link_to 'Show', @classroom %> |
<%= link_to 'Back', classrooms_path %>

app/views/classrooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Classrooms</h1>

<table>
  <thead>
    <tr>
      <th>Days</th>
      <th>Start hour</th>
      <th>End hour</th>
      <th>Start day</th>
      <th>End day</th>
      <th>User</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @classrooms.each do |classroom| %>
      <tr>
        <td><%= classroom.days %></td>
        <td><%= classroom.start_hour %></td>
        <td><%= classroom.end_hour %></td>
        <td><%= classroom.start_day %></td>
        <td><%= classroom.end_day %></td>
        <td><%= classroom.user %></td>
        <td><%= classroom.course %></td>
        <td><%= link_to 'Show', classroom %></td>
        <td><%= link_to 'Edit', edit_classroom_path(classroom) %></td>
        <td><%= link_to 'Destroy', classroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Classroom', new_classroom_path %>

app/views/classrooms/new.html.erb
<h1>New Classroom</h1>

<%= render 'form', classroom: @classroom %>

<%= link_to 'Back', classrooms_path %>

app/views/classrooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Days:</strong>
  <%= @classroom.days %>
</p>

<p>
  <strong>Start hour:</strong>
  <%= @classroom.start_hour %>
</p>

<p>
  <strong>End hour:</strong>
  <%= @classroom.end_hour %>
</p>

<p>
  <strong>Start day:</strong>
  <%= @classroom.start_day %>
</p>

<p>
  <strong>End day:</strong>
  <%= @classroom.end_day %>
</p>

<p>
  <strong>User:</strong>
  <%= @classroom.user %>
</p>

<p>
  <strong>Course:</strong>
  <%= @classroom.course %>
</p>

<%= render 'homeworks/form' %>
<% @classroom.homeworks.each do |homework| %>
    <p><%= homework.title %></p>
<% end %>

<%= link_to 'Edit', edit_course_classroom_path(@classroom) %> |
<%= link_to 'Agregar Tarea', new_course_classroom_homework_path(classroom_id: @classroom) %>