config/routes.rb
Rails.application.routes.draw do

    resources :courses do
        resources :classrooms, except: [:index] do
            resources :homeworks, except: [:index]
        end
    end
    authenticated :user do
        root 'index#home'
    end

    unauthenticated :user do
        root 'index#landing'
    end

    devise_for :users
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    #fNLviAvXLrcDO09CqUgw9w
    #E86w1EJTZtsPJ34Q2AASbg
end

app/models/homework.rb
# == Schema Information
#
# Table name: homeworks
#
#  id                   :integer          not null, primary key
#  title                :string
#  description          :text
#  delivery_date        :datetime
#  classroom_id         :integer
#  user_id              :integer
#  archivo_file_name    :string
#  archivo_content_type :string
#  archivo_file_size    :bigint
#  archivo_updated_at   :datetime
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#

class Homework < ApplicationRecord
  belongs_to :classroom
  belongs_to :user

  has_attached_file :archivo
  validates_attachment_content_type :archivo, content_type: [/png\z/, /jpe?g\z/]
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :set_homework, only: [:show, :edit, :update, :destroy]
  before_action :set_course
  before_action :set_classroom

  # GET /homeworks
  # GET /homeworks.json
  def index
    @homeworks = Homework.all
  end

  # GET /homeworks/1
  # GET /homeworks/1.json
  def show
  end

  # GET /homeworks/new
  def new
    @homework = Homework.new
  end

  # GET /homeworks/1/edit
  def edit
  end

  # POST /homeworks
  # POST /homeworks.json
  def create
    @homework = current_user.homeworks.new(homework_params)
    @homework.classroom_id = @classroom

    respond_to do |format|
      if @homework.save
        format.html { redirect_to @classroom, notice: 'Homework was successfully created.' }
        format.json { render :show, status: :created, location: @homework }
      else
        format.html { render :new }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homeworks/1
  # PATCH/PUT /homeworks/1.json
  def update
    respond_to do |format|
      if @homework.update(homework_params)
        format.html { redirect_to @homework, notice: 'Homework was successfully updated.' }
        format.json { render :show, status: :ok, location: @homework }
      else
        format.html { render :edit }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homeworks/1
  # DELETE /homeworks/1.json
  def destroy
    @homework.destroy
    respond_to do |format|
      format.html { redirect_to homeworks_url, notice: 'Homework was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homework
      @homework = Homework.find(params[:id])
    end

    def set_course
        @course = Course.find(params[:course_id])
    end

    def set_classroom
        @classroom = Classroom.find(params[:classroom_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homework_params
      params.require(:homework).permit(:title, :description, :delivery_date, :classroom_id, :user_id, :archivo)
    end
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/views/homeworks/_form.html.erb
<%= form_for([@course,@classroom, @homework]) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :delivery_date %>
    <%= form.datetime_select :delivery_date %>
  </div>

  <div class="field">
    <%= form.label :archivo %>
    <%= form.file_field :archivo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/homeworks/edit.html.erb
<h1>Editing Homework</h1>

<%= render 'form', homework: @homework %>

<%= link_to 'Show', @homework %> |
<%= link_to 'Back', homeworks_path %>

app/views/homeworks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Homeworks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Delivery date</th>
      <th>Classroom</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homeworks.each do |homework| %>
      <tr>
        <td><%= homework.title %></td>
        <td><%= homework.description %></td>
        <td><%= homework.delivery_date %></td>
        <td><%= homework.classroom %></td>
        <td><%= homework.user %></td>
        <td><%= link_to 'Show', homework %></td>
        <td><%= link_to 'Edit', edit_homework_path(homework) %></td>
        <td><%= link_to 'Destroy', homework, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Homework', new_homework_path %>

app/views/homeworks/new.html.erb
<h1>New Homework</h1>

<%= render 'form', homework: @homework %>

app/views/homeworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @homework.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @homework.description %>
</p>

<p>
  <strong>Delivery date:</strong>
  <%= @homework.delivery_date %>
</p>

<p>
  <strong>Classroom:</strong>
  <%= @homework.classroom %>
</p>

<p>
  <strong>User:</strong>
  <%= @homework.user %>
</p>

<%= link_to 'Edit', edit_homework_path(@homework) %> |
<%= link_to 'Back', homeworks_path %>